name: Repository dispatch
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  BIOME_WEBSITE_REPO: Sec-ant/website
  BIOME_PUSH_ON_MAIN_EVENT_TYPE: biome-push-on-main-event
  BIOME_PULL_REQUEST_EVENT_TYPE: biome-pull-request-event

jobs:
  repository-dispatch:
    name: Repository dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event on push
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.BIOME_REPOSITORY_DISPATCH }}
          repository: ${{ env.BIOME_WEBSITE_REPO }}
          event-type: ${{ env.BIOME_PUSH_ON_MAIN_EVENT_TYPE }}
          client-payload: '{"event": ${{ toJson(github.event) }}}'
      - name: Dispatch event on pull request
        if: ${{ github.event_name == 'pull_request'}}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BIOME_REPOSITORY_DISPATCH }}
          repository: ${{ env.BIOME_WEBSITE_REPO }}
          event-type: ${{ env.BIOME_PULL_REQUEST_EVENT_TYPE }}
          client-payload: '{"event": ${{ toJson(github.event) }}}'
      # For testing only, the payload is mocked
      - name: Dispatch event on workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.BIOME_REPOSITORY_DISPATCH }}
          repository: ${{ env.BIOME_WEBSITE_REPO }}
          event-type: ${{ env.BIOME_PUSH_ON_MAIN_EVENT_TYPE }}
          client-payload: '{"event": {"head_commit": {"id": "${{ env.GITHUB_SHA }}"}}}'
